name: quick_moe_ft
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch::pytorch>=2.1.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=11.8
  - pip
  - pip:
    - transformers>=4.36.0
    - datasets>=2.15.0
    - accelerate>=0.24.0
    - peft>=0.7.0
    - trl>=0.7.0
    - bitsandbytes>=0.41.0
    - scipy
    - sentencepiece
    - protobuf
    - tokenizers
    - einops
    - flash-attn>=2.3.0
